# Gosec configuration for GitHub security scanning
global:
  # Audit mode - finds all issues but doesn't fail the build
  audit: false
  # Confidence threshold - only report high confidence issues
  confidence: high
  # Severity threshold - only report high and medium severity
  severity: medium
  # Exclude generated files
  exclude-generated: true
  # Nosec - respect #nosec comments
  nosec: true
  # Exclude tests
  tests: false

# Exclude paths from scanning
exclude-dirs:
  - examples
  - benchmark
  - migrate
  - infrastructure
  - vendor
  - test-bolt
  - test-v1-2-0-final

# Rule-specific configuration
rules:
  # G404: Weak random is acceptable in non-production code
  G404:
    exclude:
      - "**/*_test.go"
      - "**/benchmark/**"
      - "**/examples/**"
  
  # G304: File inclusion is required for migration tools
  G304:
    exclude:
      - "**/migrate/**"
  
  # G102, G112, G114: Network configuration acceptable in examples
  G102:
    exclude:
      - "**/examples/**"
  G112:
    exclude:
      - "**/examples/**"
  G114:
    exclude:
      - "**/examples/**"