version: "2"
run:
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  enable:
    - gocognit
    - gocyclo
    - gosec
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
  disable:
    - exhaustive
    - funlen
    - goconst
    - lll
    - nlreturn
    - wsl
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - (*github.com/felixgeelhaar/bolt.Logger).Sync
        - fmt.Fprintf
        - fmt.Fprintln
        - (*os.File).Close
    gosec:
      excludes:
        - G115 # Disabled: upstream panic in gosec v2.23.0 conversion_overflow analyzer
    funlen:
      lines: 80
      statements: 50
    gocognit:
      min-complexity: 20
    goconst:
      match-constant: true
      min-len: 3
      min-occurrences: 3
      numbers: true
      min: 3
      max: 3
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 120
      tab-width: 4
    revive:
      rules:
        - name: unused-parameter
          arguments:
            - allowRegex: ^_
          severity: warning
          disabled: false
    staticcheck:
      checks:
        - all
        - -ST1003
    unparam:
      check-exported: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
          - gocognit
          - gocyclo
          - gosec
          - revive
          - unparam
          - unused
        path: _test\.go
      - linters:
          - errcheck
          - gosec
          - gocognit
          - gocyclo
          - ineffassign
          - prealloc
          - revive
          - staticcheck
          - unparam
        path: examples/
      - linters:
          - gosec
        path: bolt.go
        text: G115.*integer overflow conversion.*int8
      - linters:
          - staticcheck
        path: bolt.go
        text: QF1001
      - linters:
          - errcheck
        path: bolt.go
        source: eventPool\.Get\(\)
      - linters:
          - errcheck
        path: slog.go
        source: bufPool\.Get\(\)
      - linters:
          - errcheck
        path: bolt.go
        source: rand\.Read\(id\)
      - linters:
          - revive
        path: bolt.go
        text: parameter 'err' seems to be unused
      - linters:
          - goconst
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 50
  max-same-issues: 10
  uniq-by-line: true
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/felixgeelhaar/bolt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - examples/
