# golangci-lint configuration for Bolt
# This configuration is optimized for the Bolt zero-allocation logging library

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true

linters-settings:
  # Error check settings
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (*github.com/felixgeelhaar/bolt.Logger).Sync  # Bolt doesn't require sync
      - fmt.Fprintf     # Documentation and reporting functions
      - fmt.Fprintln    # Documentation and reporting functions
      - (*os.File).Close  # File closes in deferred statements
    ignore: "fmt:[FP].*,os:.*,encoding/json:.*" # Ignore certain packages

  # Unused parameter settings
  revive:
    rules:
      - name: unused-parameter
        severity: warning
        disabled: false
        arguments:
          - allowRegex: "^_" # Allow parameters starting with underscore

  # Constant settings
  goconst:
    min-len: 3
    min-occurrences: 3
    ignore-tests: true
    match-constant: true
    numbers: true
    min: 3
    max: 3

  # Complexity settings  
  gocyclo:
    min-complexity: 15  # Increased for complex validation logic

  # Cognitive complexity
  gocognit:
    min-complexity: 20

  # Function length
  funlen:
    lines: 80
    statements: 50

  # Line length
  lll:
    line-length: 120
    tab-width: 4

  # Unused code
  unparam:
    check-exported: false  # Don't check exported functions

  # Import organization
  goimports:
    local-prefixes: github.com/felixgeelhaar/bolt

  # Naming conventions
  stylecheck:
    checks: ["all", "-ST1003"] # Disable underscores in Go names check

linters:
  enable:
    # Essential linters
    - errcheck      # Check for unchecked errors
    - gosimple      # Suggest simplifications
    - govet         # Standard go vet checks
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced static analysis
    - typecheck     # Type checking
    - unused        # Find unused code
    
    # Code quality
    - gofmt         # Check formatting
    - goimports     # Check import formatting
    - revive        # General linting rules
    - stylecheck    # Style checks
    - unconvert     # Remove unnecessary conversions
    - unparam       # Find unused function parameters
    
    # Performance
    - prealloc      # Find slice declarations not pre-sized
    
    # Security  
    - gosec         # Security audit
    
    # Complexity
    - gocyclo       # Cyclomatic complexity
    - gocognit      # Cognitive complexity
    
  disable:
    # Disabled due to specific Bolt requirements
    - goconst       # Too many false positives in migration code
    - funlen        # Some functions need to be longer for performance
    - lll           # Some long lines are acceptable for readability
    - wsl           # Whitespace linter too strict
    - nlreturn      # Return style too restrictive
    - exhaustive    # Switch exhaustiveness not always needed

issues:
  # Exclude specific issues
  exclude-rules:
    # Ignore unused parameters in test files
    - path: "_test\\.go"
      linters:
        - unused
        - unparam
        - revive
    
    # Ignore certain issues in migration packages (legacy code)
    - path: "migrate/"
      linters:
        - goconst      # Migration code has many repeated strings
        - errcheck     # Legacy patterns may not check all errors
        - stylecheck   # Migration examples don't need strict documentation style
    
    # Ignore issues in benchmark validation (complex analysis code)
    - path: "benchmark/validation/"
      linters:
        - gocyclo      # Complex validation logic
        - gocognit     # Analysis functions are inherently complex
        - funlen       # Analysis functions need to be comprehensive
        - errcheck     # Non-critical analysis code, errors not always needed
        - unparam      # Analysis functions may have consistent parameters
    
    # Allow builtin redefinition in specific validation file
    - path: "benchmark/validation/performance_validator.go"
      text: "redefinition of the built-in function"
      linters:
        - revive
    
    # Allow exported type name stuttering in validation package
    - path: "benchmark/validation/"
      text: "type name will be used.*stutters"
      linters:
        - revive
    
    # Ignore indent-error-flow in complex validation logic
    - path: "benchmark/validation/performance_validator.go"
      text: "if block ends with a return statement"
      linters:
        - revive
    
    # Allow unused parameters in specific test functions
    - path: "race_test.go"
      text: "parameter.*seems to be unused"
      linters:
        - revive
    
    # Allow unused error in specific bolt.go function
    - path: "bolt.go"
      line: 417
      text: "parameter 'err' seems to be unused"
      linters:
        - revive
    
    # Exclude specific errcheck issues in bolt.go (core performance paths where errors are intentionally ignored for performance)
    - path: "bolt.go"
      line: 493
      linters:
        - errcheck
    - path: "bolt.go"  
      line: 846
      linters:
        - errcheck
    
    # Exclude errcheck issues in performance validator (non-critical analysis code)
    - path: "benchmark/validation/performance_validator.go"
      line: 265
      linters:
        - errcheck
    - path: "benchmark/validation/performance_validator.go"
      line: 266
      linters:
        - errcheck
    - path: "benchmark/validation/performance_validator.go"
      line: 267
      linters:
        - errcheck
    - path: "benchmark/validation/performance_validator.go"
      line: 268
      linters:
        - errcheck
    - path: "benchmark/validation/performance_validator.go"
      line: 363
      linters:
        - errcheck
    - path: "benchmark/validation/performance_validator.go"
      line: 364
      linters:
        - errcheck
    - path: "benchmark/validation/performance_validator.go"
      line: 383
      linters:
        - errcheck
    - path: "benchmark/validation/performance_validator.go"
      line: 384
      linters:
        - errcheck
    
    # Ignore errcheck in benchmark packages (non-critical test/analysis code)
    - path: "benchmark/"
      linters:
        - errcheck
        - unparam
    
    # Ignore errcheck in example packages (demonstration code)
    - path: "examples/"
      linters:
        - errcheck
    
    # Ignore errcheck in test files (testing code)
    - path: "_test\\.go"
      linters:
        - errcheck

  # Maximum issues count per one linter
  max-issues-per-linter: 50
  
  # Maximum count of issues with the same text
  max-same-issues: 10
  
  # Don't skip warning about long lines
  exclude-use-default: false