# AlertManager Configuration for Bolt Logging Library
# Production-ready alerting with escalation paths and routing

global:
  # SMTP configuration for email alerts
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'alerts@bolt-logging.example.com'
  smtp_auth_username: 'alerts@bolt-logging.example.com'
  smtp_auth_password: 'smtp_password_here'
  smtp_require_tls: true

  # Slack webhook for team notifications
  slack_api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'

  # Default template files
  templates:
    - '/etc/alertmanager/templates/*.tmpl'

# Routing configuration - defines how alerts are grouped and routed
route:
  # Root route - catches all alerts
  group_by: ['alertname', 'severity', 'component']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default-receiver'
  
  # Child routes for specific alert routing
  routes:
    # Critical Bolt performance alerts
    - match:
        component: bolt-logging
        severity: critical
      receiver: 'bolt-critical-alerts'
      group_wait: 5s
      repeat_interval: 5m
      continue: true

    # Warning level alerts
    - match:
        component: bolt-logging  
        severity: warning
      receiver: 'bolt-warning-alerts'
      group_wait: 30s
      repeat_interval: 30m

    # Business metric anomalies
    - match:
        category: business
      receiver: 'business-alerts'
      group_wait: 60s
      repeat_interval: 6h

    # Capacity planning alerts
    - match:
        category: capacity
      receiver: 'capacity-alerts'
      group_wait: 60s
      repeat_interval: 4h

    # Infrastructure alerts
    - match_re:
        alertname: '(BoltHandlerDown|BoltDiskSpaceLow)'
      receiver: 'infrastructure-alerts'
      group_wait: 10s
      repeat_interval: 15m

# Inhibition rules - suppress certain alerts when others are firing
inhibit_rules:
  # Suppress warning latency alerts when critical ones are active
  - source_match:
      alertname: 'BoltLoggingLatencyHigh'
      severity: 'critical'
    target_match:
      alertname: 'BoltLoggingLatencyWarning'
    equal: ['instance', 'component']

  # Suppress individual handler alerts when service is down
  - source_match:
      alertname: 'BoltHandlerDown'
    target_match_re:
      alertname: 'Bolt.*'
    equal: ['instance']

  # Suppress performance alerts during high error rates
  - source_match:
      alertname: 'BoltLoggingErrorRateCritical'
    target_match:
      category: 'performance'
    equal: ['instance']

# Receiver configurations
receivers:
  # Default receiver for unmatched alerts
  - name: 'default-receiver'
    email_configs:
      - to: 'devops-team@example.com'
        subject: '[Bolt] Default Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Labels: {{ range .Labels.SortedPairs }}{{ .Name }}="{{ .Value }}" {{ end }}
          {{ end }}

  # Critical Bolt performance alerts
  - name: 'bolt-critical-alerts'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#alerts-critical'
        title: '🔴 CRITICAL: Bolt Logging Alert'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          *Runbook:* {{ .Annotations.runbook_url }}
          {{ end }}
        send_resolved: true
    
    email_configs:
      - to: 'bolt-oncall@example.com'
        subject: '[CRITICAL] Bolt Alert: {{ .GroupLabels.alertname }}'
        body: |
          CRITICAL ALERT for Bolt Logging Library
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          Runbook: {{ .Annotations.runbook_url }}
          
          Time: {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          {{ end }}

    # PagerDuty integration for critical alerts
    pagerduty_configs:
      - service_key: 'your-pagerduty-service-key'
        description: '{{ .GroupLabels.alertname }} - {{ .CommonAnnotations.summary }}'
        details:
          alert_count: '{{ .Alerts | len }}'
          alerts: |
            {{ range .Alerts }}
            - {{ .Annotations.summary }}
            {{ end }}

  # Warning level alerts
  - name: 'bolt-warning-alerts'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#alerts-warning'
        title: '⚠️ WARNING: Bolt Performance Issue'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Instance:* {{ .Labels.instance }}
          {{ end }}
        send_resolved: true

    email_configs:
      - to: 'bolt-team@example.com'
        subject: '[WARNING] Bolt Alert: {{ .GroupLabels.alertname }}'

  # Business metric alerts
  - name: 'business-alerts'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#business-metrics'
        title: '📊 Business Metric Alert'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          {{ end }}

  # Capacity planning alerts
  - name: 'capacity-alerts'
    email_configs:
      - to: 'capacity-planning@example.com'
        subject: '[CAPACITY] Bolt Resource Alert: {{ .GroupLabels.alertname }}'
        body: |
          Capacity planning alert for Bolt logging infrastructure.
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Current Value: {{ .Annotations.value }}
          {{ end }}
          
          Please review resource allocation and scaling policies.

  # Infrastructure alerts
  - name: 'infrastructure-alerts'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#infrastructure'
        title: '🏗️ Infrastructure Alert'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Runbook:* {{ .Annotations.runbook_url }}
          {{ end }}

    email_configs:
      - to: 'infrastructure-team@example.com'
        subject: '[INFRA] Bolt Infrastructure Alert: {{ .GroupLabels.alertname }}'

# Template definitions for custom alert formatting
templates:
  - name: 'bolt-alert-template'
    template: |
      {{ define "bolt.title" }}
      [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] 
      Bolt {{ .GroupLabels.alertname }}
      {{ end }}

      {{ define "bolt.text" }}
      {{ range .Alerts }}
      **Alert:** {{ .Annotations.summary }}
      **Description:** {{ .Annotations.description }}
      **Instance:** {{ .Labels.instance }}
      **Component:** {{ .Labels.component }}
      **Severity:** {{ .Labels.severity }}
      {{ if .Annotations.runbook_url }}**Runbook:** {{ .Annotations.runbook_url }}{{ end }}
      **Start Time:** {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
      {{ if .EndsAt }}**End Time:** {{ .EndsAt.Format "2006-01-02 15:04:05 UTC" }}{{ end }}
      ---
      {{ end }}
      {{ end }}

# Webhook configurations for custom integrations
receivers:
  - name: 'webhook-receiver'
    webhook_configs:
      - url: 'http://webhook-server:9093/webhook'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'webhook-user'
            password: 'webhook-password'

# Time-based routing (silence alerts during maintenance windows)
time_intervals:
  - name: 'maintenance-window'
    time_intervals:
      - times:
          - start_time: '02:00'
            end_time: '04:00'
        weekdays: ['saturday', 'sunday']

# Mute/silence configurations
silences:
  # Example: Silence all alerts for a specific instance during maintenance
  - matchers:
      - name: instance
        value: 'bolt-app-1:8080'
    starts_at: '2024-01-01T02:00:00Z'
    ends_at: '2024-01-01T04:00:00Z'
    created_by: 'maintenance-system'
    comment: 'Scheduled maintenance window'