# Jaeger Distributed Tracing Configuration for Bolt Logging Library
# Production-ready tracing setup with sampling and performance optimization

# Jaeger Collector Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-configuration
  namespace: monitoring
data:
  # Collector configuration
  collector.yaml: |
    collector:
      # High-performance queue configuration for Bolt's low-latency requirements
      queue-size: 10000
      queue-size-memory: 1000
      num-workers: 50
      
      # Batch processing for efficiency
      write-buffer-size: 16384
      
      # Health check endpoint
      health-check-http-port: 14269
      
      # Metrics endpoint for Prometheus
      admin-http-port: 14268
      
      # Kafka configuration for high-throughput environments
      kafka:
        producer:
          brokers:
            - kafka:9092
          topic: jaeger-spans
          batch-size: 1000
          batch-timeout: 1s
          # High-performance settings for Bolt's zero-allocation goals
          compression-type: snappy
          batch-linger: 5ms
          buffer-memory: 67108864
          
      # Elasticsearch storage for long-term trace retention
      es:
        server-urls: http://elasticsearch:9200
        index-prefix: jaeger
        create-index-templates: true
        # Performance optimization for high-volume logging
        bulk:
          size: 10000000  # 10MB batches
          workers: 8
          flush-interval: 1s
        # Index rollover for log management
        index-date-separator: "-"
        index-rollover-frequency-hour: 24
        max-doc-count: 100000000

  # Agent configuration
  agent.yaml: |
    agent:
      # High-frequency sampling for performance monitoring
      strategies:
        default_strategy:
          type: probabilistic
          param: 0.1  # 10% sampling for production
          
        # Higher sampling for Bolt-specific traces
        per_service_strategies:
          - service: "bolt-logging"
            type: probabilistic
            param: 0.5  # 50% sampling for critical logging operations
            
          - service: "bolt-app"
            type: adaptive
            param: 0.25
            max_traces_per_second: 1000
            
      # Agent performance configuration
      processors:
        - jaeger-compact
        - jaeger-binary
      
      # Reporting configuration optimized for Bolt's latency requirements
      reporter:
        queue-size: 5000
        buffer-flush-interval: 1s
        log-spans: false  # Disable to avoid logging loops
        
      # Health and admin endpoints
      health-check-http-port: 5778
      admin-http-port: 14271

  # Jaeger Query Service Configuration
  query.yaml: |
    query:
      # High-performance query configuration
      max-clock-skew-adjustment: 10s
      
      # UI configuration
      ui:
        header-color: "#1f77b4"
        
      # Query limits for performance
      max-trace-duration: 48h
      
      # ES query configuration
      es:
        max-span-age: 72h
        max-num-spans: 10000000
        adaptive-sampling-lookback: 2m

---
# Jaeger All-in-One Deployment for Development
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-all-in-one
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger-all-in-one
  template:
    metadata:
      labels:
        app: jaeger-all-in-one
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.50
        ports:
        - containerPort: 16686  # Jaeger UI
        - containerPort: 14268  # HTTP collector
        - containerPort: 14250  # gRPC collector
        - containerPort: 6831   # UDP agent (compact)
        - containerPort: 6832   # UDP agent (binary)
        - containerPort: 5778   # HTTP config
        env:
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
        - name: COLLECTOR_ZIPKIN_HOST_PORT
          value: ":9411"
        - name: MEMORY_MAX_TRACES
          value: "50000"
        # Performance optimizations for Bolt
        - name: SPAN_STORAGE_TYPE
          value: "memory"
        - name: JAEGER_SAMPLER_TYPE
          value: "adaptive"
        - name: JAEGER_SAMPLER_PARAM
          value: "0.1"
        - name: JAEGER_SAMPLER_MAX_TRACES_PER_SECOND
          value: "1000"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

---
# Production Jaeger Collector Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-collector
  namespace: monitoring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jaeger-collector
  template:
    metadata:
      labels:
        app: jaeger-collector
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "14268"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: jaeger-collector
        image: jaegertracing/jaeger-collector:1.50
        ports:
        - containerPort: 14267  # TChannel
        - containerPort: 14268  # HTTP
        - containerPort: 14269  # Health check
        - containerPort: 14250  # gRPC
        - containerPort: 9411   # Zipkin
        env:
        - name: SPAN_STORAGE_TYPE
          value: "elasticsearch"
        - name: ES_SERVER_URLS
          value: "http://elasticsearch:9200"
        - name: ES_INDEX_PREFIX
          value: "jaeger"
        - name: COLLECTOR_QUEUE_SIZE
          value: "10000"
        - name: COLLECTOR_NUM_WORKERS
          value: "50"
        # High-performance settings for Bolt
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
        - name: KAFKA_PRODUCER_BROKERS
          value: "kafka:9092"
        - name: KAFKA_PRODUCER_TOPIC
          value: "jaeger-spans"
        volumeMounts:
        - name: jaeger-config
          mountPath: /etc/jaeger/
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      - name: jaeger-config
        configMap:
          name: jaeger-configuration

---
# Jaeger Agent DaemonSet for Node-level Collection
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: jaeger-agent
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: jaeger-agent
  template:
    metadata:
      labels:
        app: jaeger-agent
    spec:
      containers:
      - name: jaeger-agent
        image: jaegertracing/jaeger-agent:1.50
        ports:
        - containerPort: 5775   # UDP zipkin-compact
        - containerPort: 6831   # UDP jaeger-compact
        - containerPort: 6832   # UDP jaeger-binary
        - containerPort: 5778   # HTTP config
        - containerPort: 14271  # HTTP admin
        env:
        - name: REPORTER_GRPC_HOST_PORT
          value: "jaeger-collector:14250"
        - name: AGENT_TAGS
          value: "node=$(NODE_NAME),cluster=production"
        - name: LOG_LEVEL
          value: "INFO"
        # Performance optimizations
        - name: PROCESSOR_JAEGER_BINARY_SERVER_MAX_PACKET_SIZE
          value: "4096"
        - name: PROCESSOR_JAEGER_COMPACT_SERVER_MAX_PACKET_SIZE
          value: "4096"
        - name: REPORTER_GRPC_RETRY_MAX
          value: "5"
        envFrom:
        - fieldRef:
            fieldPath: spec.nodeName
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
        - name: jaeger-config
          mountPath: /etc/jaeger/
      volumes:
      - name: jaeger-config
        configMap:
          name: jaeger-configuration
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

---
# Jaeger Query Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-query
  namespace: monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jaeger-query
  template:
    metadata:
      labels:
        app: jaeger-query
    spec:
      containers:
      - name: jaeger-query
        image: jaegertracing/jaeger-query:1.50
        ports:
        - containerPort: 16686  # HTTP UI
        - containerPort: 16687  # Admin
        env:
        - name: SPAN_STORAGE_TYPE
          value: "elasticsearch"
        - name: ES_SERVER_URLS
          value: "http://elasticsearch:9200"
        - name: ES_INDEX_PREFIX
          value: "jaeger"
        - name: QUERY_MAX_CLOCK_SKEW_ADJUSTMENT
          value: "10s"
        # Performance settings
        - name: QUERY_TIMEOUT
          value: "30s"
        - name: ES_MAX_SPAN_AGE
          value: "72h"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"

---
# Service definitions
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: monitoring
  labels:
    app: jaeger-collector
spec:
  ports:
  - port: 14267
    name: tchannel
  - port: 14268
    name: http
  - port: 14250
    name: grpc
  - port: 9411
    name: zipkin
  selector:
    app: jaeger-collector

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: monitoring
  labels:
    app: jaeger-query
spec:
  ports:
  - port: 16686
    name: http-ui
    targetPort: 16686
  selector:
    app: jaeger-query
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  namespace: monitoring
  labels:
    app: jaeger-agent
spec:
  ports:
  - port: 5775
    name: zipkin-compact
  - port: 6831
    name: jaeger-compact
  - port: 6832
    name: jaeger-binary
  - port: 5778
    name: http-config
  clusterIP: None
  selector:
    app: jaeger-agent