name: Bug Report
description: Report a bug or unexpected behavior
title: "[BUG]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide a minimal code example that reproduces the issue
      placeholder: |
        ```go
        package main
        
        import "github.com/felixgeelhaar/logma"
        
        func main() {
            // Your reproduction code here
        }
        ```
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: Output of `go version`
      placeholder: go version go1.21.0 darwin/arm64
    validations:
      required: true

  - type: input
    id: logma-version
    attributes:
      label: Logma Version
      description: Version of Logma you're using
      placeholder: v1.0.0
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - FreeBSD
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs/Stack Trace
      description: Any relevant logs, stack traces, or error messages
      render: text
      placeholder: Paste any relevant logs or stack traces here...

  - type: textarea
    id: performance
    attributes:
      label: Performance Impact
      description: If this is a performance issue, include benchmark results
      placeholder: |
        Include benchmark results:
        ```
        BenchmarkBefore-8    1000000    1234 ns/op    456 B/op    7 allocs/op
        BenchmarkAfter-8     1000000    5678 ns/op    890 B/op   12 allocs/op
        ```

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided a minimal reproduction case
          required: true
        - label: I have included relevant version information
          required: true