blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/felixgeelhaar/bolt/discussions
    about: Ask questions or start discussions about Bolt usage and features
  - name: Security Vulnerability
    url: https://github.com/felixgeelhaar/bolt/security/advisories/new
    about: Report security vulnerabilities privately