name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide detailed information about your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's your use case?
      placeholder: Describe the problem or use case...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution to the problem
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: api-design
    attributes:
      label: API Design
      description: If applicable, propose the API design for this feature
      placeholder: |
        ```go
        // Example API design
        logger.NewFeature().SomeMethod().Msg("example")
        ```

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions have you considered?
      placeholder: Describe alternative approaches...

  - type: dropdown
    id: performance-impact
    attributes:
      label: Performance Impact
      description: What's the expected performance impact?
      options:
        - No impact expected
        - Might improve performance
        - Might reduce performance
        - Performance critical - needs benchmarking
        - Unknown
    validations:
      required: true

  - type: dropdown
    id: breaking-change
    attributes:
      label: Breaking Change
      description: Would this be a breaking change?
      options:
        - No - backward compatible
        - Yes - breaking change
        - Unsure
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      description: Are you willing to implement this feature?
      options:
        - label: I can implement this feature
        - label: I need help implementing this feature
        - label: I cannot implement this feature

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, examples, or screenshots about the feature request
      placeholder: Add any other context here...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have described the use case clearly
          required: true
        - label: I have considered the performance implications
          required: true