homepage: "https://github.com/klarlabs-studio/bolt"
language: go
primary_contact: "felix@felixgeelhaar.de"
auto_ccs:
  - "felix@felixgeelhaar.de"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
main_repo: "https://github.com/klarlabs-studio/bolt"
file_github_issue: true
