apiVersion: v1
kind: ServiceAccount
metadata:
  name: bolt-app
  namespace: production
  labels:
    app: bolt-app
    version: v1.3.0
automountServiceAccountToken: true

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bolt-app
  namespace: production
  labels:
    app: bolt-app
    version: v1.3.0
rules:
# Allow reading ConfigMaps for configuration
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]

# Allow reading Secrets for credentials
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]

# Allow reading pod info for metadata injection
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bolt-app
  namespace: production
  labels:
    app: bolt-app
    version: v1.3.0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bolt-app
subjects:
- kind: ServiceAccount
  name: bolt-app
  namespace: production
