apiVersion: v1
kind: Service
metadata:
  name: bolt-app
  namespace: production
  labels:
    app: bolt-app
    version: v1.3.0
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: bolt-app
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: grpc
    port: 9090
    targetPort: grpc
    protocol: TCP
  - name: metrics
    port: 8080
    targetPort: http
    protocol: TCP
  sessionAffinity: None
